name: ASP.NET (s390x)
run-name: "Event: ${{ github.event_name }}; ${{ github.event_name == 'pull_request' && format('PR: {0}; ', github.event.number) || format('Branch: {0}; ', github.ref_name)}}${{ github.event_name == 'workflow_dispatch' && format('Version: {0}', inputs.version) || '' }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: '7.0.16'
  create:
    branches:
    - 'releases/*'
  push:
    branches:
    - '**'
    paths:
    - '.github/workflows/aspnet-s390x.yml'
    - '.github/workflows/build-and-publish.yml'
  pull_request:
    branches:
    - 'main'
    - 'releases/*'
    types:
    - opened
    - reopened
    - synchronize

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: write
    secrets: inherit
    with:
      job-name-prefix: "${{ github.workflow }} "
      repo-url: dotnet/aspnetcore
      checkout-tag: v${{ github.event_name == 'workflow_dispatch' && inputs.version || '7.0.16' }}
      runtime-arch: s390x
      runtime-configuration: Release
      build-commands: |
        export ROOTFS_DIR=/crossfs/${RUNTIME_ARCH}
        chmod +x ./eng/build.sh
        ./eng/build.sh --os-name ${RUNTIME_OS} --arch ${RUNTIME_ARCH} --configuration ${RUNTIME_CONFIGURATION} --pack --all --no-build-nodejs --no-build-java --no-build-installers /p:OnlyPackPlatformSpecificPackages=true /p:SkipTestBuild=true /p:PostBuildSign=true /p:DotNetBuildFromSource=true
