name: Build And Publish

on:
  workflow_call:
    inputs:
      repo-url:
        description: 'Repository URL to checkout'
        required: true
        type: string
      checkout-tag:
        description: 'Repository tag to checkout'
        required: true
        type: string
      runtime-os:
        description: 'Type of the OS to build dotnet'
        default: 'Linux'
        required: false
        type: string
      runtime-arch:
        description: 'Architecture of the OS to build dotnet'
        required: true
        type: string
      runtime-configuration:
        description: 'Configuration to build dotnet'
        required: true
        type: string
      container:
        description: 'Container specs to use for build'
        default: '{ "image": "ghcr.io/gold-bull/dotnet-build-deps:ubuntu-22.04-latest" }'
        required: false
        type: string
      build-commands:
        description: 'Commands to run post checkout'
        required: true
        type: string

env:
  RUNTIME_OS: ${{ inputs.runtime-os }}
  RUNTIME_ARCH: ${{ inputs.runtime-arch }}
  RUNTIME_CONFIGURATION: ${{ inputs.runtime-configuration }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ fromJSON(inputs.container) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: self

      - name: Checkout .NET repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo-url }}
          submodules: true
          ref: ${{ inputs.checkout-tag }}
          path: dotnet

      - name: Run commands
        run: ${{ inputs.build-commands }}
        working-directory: ./dotnet

      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: |
            artifacts/packages/${{ env.RUNTIME_CONFIGURATION }}/Shipping/**/*.nupkg
            !artifacts/packages/${{ env.RUNTIME_CONFIGURATION }}/Shipping/**/*.symbols.nupkg
          retention-days: ${{ startsWith(github.ref, 'refs/heads/releases/') && 30 || 7 }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archives
          path: |
            artifacts/packages/${{ env.RUNTIME_CONFIGURATION }}/Shipping/**/*.tar.*
          retention-days: ${{ startsWith(github.ref, 'refs/heads/releases/') && 30 || 7 }}

  publish:
    if: ${{ startsWith(github.ref, 'refs/heads/releases/') }}
    runs-on: ubuntu-latest
    needs: build
    concurrency: packages-publish
    environment: packages-publish
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuget-packages

      - name: Upload Packages
        run: |
          dotnet nuget add source --username USERNAME --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push "**/*.nupkg" --source github --skip-duplicate --no-symbols
