name: .NET Runtime (s390x)

on:
  workflow_dispatch:

  push:
    branches:
      - 'releases/**'
    tags:
      - v*
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      repo-url: dotnet/runtime
      checkout-tag: v6.0.16
      runtime-arch: s390x
      runtime-configuration: Release
      build-commands: |
        export ROOTFS_DIR=/crossfs/${RUNTIME_ARCH}
        chmod +x ./build.sh
        ./build.sh --subset mono+libs+host+packs --cross --os ${RUNTIME_OS} --arch ${RUNTIME_ARCH} --configuration ${RUNTIME_CONFIGURATION}