name: .NET Runtime (s390x)
run-name: "Event: ${{ github.event_name }}; Branch: ${{ github.ref_name }}; Version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || '6.0.16' }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

  push:
    branches:
      - 'releases/**'
    tags:
      - v*
    paths:
      - '.github/workflows/runtime-s390x.yml'
      - '.github/workflows/build-and-publish.yml'

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: write
    secrets: inherit
    with:
      repo-url: dotnet/runtime
      checkout-tag: v${{ github.event_name == 'workflow_dispatch' && inputs.version || '6.0.16' }}
      runtime-arch: s390x
      runtime-configuration: Release
      build-commands: |
        git apply ../self/patches/001_init-complier_lld.patch
        
        export ROOTFS_DIR=/crossfs/${RUNTIME_ARCH}
        chmod +x ./build.sh
        ./build.sh --subset mono+libs+host+packs --cross --os ${RUNTIME_OS} --arch ${RUNTIME_ARCH} --configuration ${RUNTIME_CONFIGURATION}
