name: .NET Runtime (s390x)
run-name: "Event: ${{ github.event_name }}; ${{ github.event_name == 'pull_request' && format('PR: {0}; ', github.event.number) || format('Branch: {0}; ', github.ref_name)}}${{ github.event_name == 'workflow_dispatch' && format('Version: {0}', inputs.version) || '' }}"

on:
  workflow_dispatch:
    inputs:
      version:
          description: 'Version'
          required: true
          default: '8.0.2'
  create:
    branches:
    - 'releases/*'
  push:
    branches:
    - '**'
    paths:
    - '.github/workflows/runtime-s390x.yml'
    - '.github/workflows/build-and-publish.yml'
  pull_request:
    branches:
    - 'main'
    - 'releases/*'
    types:
    - opened
    - reopened
    - synchronize

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: write
    secrets: inherit
    with:
      job-name-prefix: ${{ github.workflow }}
      repo-url: dotnet/runtime
      checkout-tag: v${{ github.event_name == 'workflow_dispatch' && inputs.version || '8.0.2' }}
      runtime-arch: s390x
      runtime-configuration: Release
      build-commands: |
        export ROOTFS_DIR=/crossfs/${RUNTIME_ARCH}
        chmod +x ./build.sh
        ./build.sh --subset mono+libs+host+packs --cross --os ${RUNTIME_OS} --arch ${RUNTIME_ARCH} --configuration ${RUNTIME_CONFIGURATION}
